# Test text matching

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout\@v2

    - name: Install JSON
      run: |
        sudo cpan install -T JSON

    - name: Install Data::Table::Text
      run: |
        sudo cpan install -T Data::Table::Text

    - name: Install Date::Manip
      run: |
        sudo cpan install -T Date::Manip

    - name: Install Digest::SHA1
      run: |
        sudo cpan install -T Digest::SHA1

    - name: Install GitHub Crud
      run: |
        sudo cpan install -T GitHub::Crud

    - name: Install Math::Permute::List
      run: |
        sudo cpan install -T Math::Permute::List

    - name: Install Text::Match
      run: |
        sudo cpan install -T Text::Match

    - name: Test
      run: |
        perl matchText.pl > output.txt
        cat output.txt

    - name: Upload results
      run: |
         GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} perl -MGitHub::Crud -e "GitHub::Crud::writeFileFromFileFromCurrentRun q(output.txt)"
